import 'dart:io';
import 'package:path_provider/path_provider.dart';

/// Native (dart:io) platform helpers — only compiled on native targets.
class PlatformHelper {
  static bool get isAndroid => Platform.isAndroid;
  static bool get isWindows => Platform.isWindows;
  static bool get isLinux => Platform.isLinux;
  static bool get isIOS => Platform.isIOS;
  static bool get isMacOS => Platform.isMacOS;

  static bool fileExists(String path) => File(path).existsSync();

  static String get pathSeparator => Platform.pathSeparator;

  static Future<void> cleanupTempFiles(String dirPath) async {
    try {
      final dir = Directory(dirPath);
      if (!await dir.exists()) return;
      final tempFiles = dir.listSync().where((f) =>
          f is File &&
          f.path.contains('playback_safe_') &&
          f.path.endsWith('.flac'));
      for (final file in tempFiles) {
        try {
          file.deleteSync();
        } catch (_) {}
      }
    } catch (_) {}
  }

  /// Read an environment variable, returns [fallback] if not set
  static String getEnv(String key, {String fallback = ''}) =>
      Platform.environment[key] ?? fallback;

  /// Returns file size in bytes, 0 if not found
  static int fileSize(String path) {
    try {
      return File(path).lengthSync();
    } catch (_) {
      return 0;
    }
  }

  /// Deletes a file, ignores errors
  static void deleteFile(String path) {
    try {
      final f = File(path);
      if (f.existsSync()) f.deleteSync();
    } catch (_) {}
  }

  /// Creates a directory recursively if it doesn't exist
  static Future<void> ensureDir(String path) async {
    final dir = Directory(path);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
  }

  /// Rename a file
  static Future<void> renameFile(String from, String to) async {
    await File(from).rename(to);
  }

  /// Get the path for storing history file
  static String? getHistoryFilePath(String fileName) {
    // Returns null; the async version below is used
    return null;
  }

  /// Write a string to a file
  static Future<void> writeFile(String path, String content) async {
    await File(path).writeAsString(content);
  }

  /// Read a file as string, returns null if not found
  static Future<String?> readFile(String path) async {
    try {
      final f = File(path);
      if (await f.exists()) return await f.readAsString();
      return null;
    } catch (_) {
      return null;
    }
  }

  /// Create global mpv.conf to override TLS backend and probing sizes on Windows
  static void ensureMpvConfig() {
    if (!Platform.isWindows) return;
    try {
      final appData = Platform.environment['APPDATA'];
      if (appData != null) {
        final mpvDir = Directory('$appData\\mpv');
        if (!mpvDir.existsSync()) {
          mpvDir.createSync(recursive: true);
        }
        final mpvConf = File('${mpvDir.path}\\mpv.conf');
        mpvConf.writeAsStringSync('''
# MPV configuration generated by BeatBoss
# TLS: use openssl — mbedtls has reconnect issues with Tidal CDN
tls-backend=openssl

# Probing: give lavf time to analyze DASH manifests
demuxer-lavf-probesize=100000000
demuxer-lavf-analyzeduration=30

# Cache: RAM-ONLY. DASH needs cache to stitch segments, but disk caching
# causes file-lock collisions between consecutive streams on Windows.
cache=yes
cache-on-disk=no
demuxer-max-bytes=20MiB
demuxer-max-back-bytes=4MiB

# Keep mpv alive but dormant between tracks (prevents zombie threads)
idle=yes

# Audio output: explicit WASAPI
ao=wasapi

# Network
network-timeout=30
''');
        print('[PlatformHelper] Successfully created global mpv.conf at: ${mpvConf.path}');
      }
    } catch (e) {
      print('[PlatformHelper] Failed to create mpv.conf: $e');
    }
  }
}
